# Generated by Django 3.0.5 on 2020-05-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChrClass',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hits', models.CharField(max_length=3000)),
                ('saving_throwth', models.CharField(max_length=3000)),
                ('special_features', models.CharField(max_length=3000)),
                ('props_and_langs', models.CharField(max_length=3000)),
                ('in_growh', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('characteristic_increase', models.CharField(max_length=3000)),
                ('special_features', models.CharField(max_length=3000)),
                ('props_and_langs', models.CharField(max_length=3000)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('align', models.CharField(choices=[('LG', 'lawful good'), ('NG', 'neutral good'), ('CG', 'chaotic good'), ('LN', 'lawful neutral'), ('NN', 'truly neutral(boring)'), ('CN', 'chaotic neutral'), ('LE', 'lawful evil'), ('NE', 'neutral evil'), ('CE', 'chaotic evil')], max_length=2)),
                ('lvl', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('acrobatic', models.BooleanField(default=False)),
                ('animal_handling', models.BooleanField(default=False)),
                ('arcana', models.BooleanField(default=False)),
                ('athletics', models.BooleanField(default=False)),
                ('deception', models.BooleanField(default=False)),
                ('history', models.BooleanField(default=False)),
                ('insight', models.BooleanField(default=False)),
                ('intimidation', models.BooleanField(default=False)),
                ('investigation', models.BooleanField(default=False)),
                ('medicine', models.BooleanField(default=False)),
                ('nature', models.BooleanField(default=False)),
                ('perception', models.BooleanField(default=False)),
                ('performance', models.BooleanField(default=False)),
                ('persuasion', models.BooleanField(default=False)),
                ('religion', models.BooleanField(default=False)),
                ('sleight_of_hand', models.BooleanField(default=False)),
                ('stealth', models.BooleanField(default=False)),
                ('survival', models.BooleanField(default=False)),
                ('equipment', models.CharField(blank=True, max_length=3000)),
                ('weapons', models.CharField(blank=True, max_length=3000)),
                ('goldCoins', models.IntegerField()),
                ('silverCoins', models.IntegerField()),
                ('copperCoins', models.IntegerField()),
                ('traits', models.CharField(max_length=3000)),
                ('ideals', models.CharField(max_length=3000)),
                ('bonds', models.CharField(max_length=3000)),
                ('flaws', models.CharField(max_length=3000)),
                ('organizations', models.CharField(max_length=3000)),
                ('backstory', models.CharField(max_length=3000)),
                ('additional', models.CharField(max_length=3000)),
                ('treasure', models.CharField(max_length=3000)),
                ('chrclass', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.ChrClass')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.User')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Race')),
            ],
        ),
    ]
