# Generated by Django 3.0.5 on 2020-05-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='temp_hit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
