# Generated by Django 3.0.5 on 2020-05-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_character_temp_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor_class',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
